# Generated by Django 4.0.6 on 2023-06-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_pergunta_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='alternativa_correta',
            field=models.BooleanField(default='correta'),
        ),
    ]
