# Generated by Django 4.0.6 on 2023-06-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0003_alternativa_alternativa_correta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='alternativa_correta',
        ),
    ]
