# Generated by Django 4.0.6 on 2023-07-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuladao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='nome_simulado',
            field=models.CharField(default='digite o nome do seu simulado', max_length=100),
        ),
    ]
