# Generated by Django 4.0.6 on 2023-07-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simuladao', '0005_remove_usuario_simulado_simulado_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='simulado',
            field=models.ForeignKey(default='name', on_delete=django.db.models.deletion.CASCADE, to='simuladao.simulado'),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='nome_simulado',
            field=models.CharField(default='digite o nome do seu simulado', max_length=100),
        ),
    ]
