# Generated by Django 4.0.6 on 2023-07-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simuladao', '0008_remove_usuario_simulado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='resposta_correta',
            new_name='resposta',
        ),
    ]
